### ISSUE TITLE
Домашка №3 (ООП)

### ISSUE THREAD

**Issue by kottans-net** [shamanishche/Kottans_Repo#4]
Предлагаем вам выполнить домашку по ООП https://github.com/Zaknafeyn/OOP.Task

**Comment by shamanishche** [comment]
Виконана домашка по ООП:

https://github.com/shamanishche/Kottans_Repo/tree/master/HW3_OOP

Дякую!

**Comment by zaknafeyn** [comment]
Проверено

Несколько комментариев:
1. Метод Move общий для всех классов, его стоит вынести в базовый класс ShapeBase
2. Неверно вычисляется площадь фигур. Множитель дожен применятся к каждой стороне фигуры. Например для прямоугольника формула должна быть такая: Multiplier \* _edge1 \* Multiplier \* _edge2;
3. Для прямоугольного теугольника есть более рациональная формула (_edge1 \* edge2 / 2) для рассчета площади, лучше использовать ее вместо формулы Герона.
4.  Периметр для равностороннего и прямоугольно треугольника считаеться неверно, не смотря на то что тесты проходят. Проверь еще раз, а лучше напиши свой тест для равностороннего треугольника
